server:
  port: 8888
  ssl:
    enabled: false
spring:
  application:
    name: BiliAF
  datasource:
    url: jdbc:postgresql://localhost:5432/bibliaf
    username: postgres
    password: postdba
    jpa:
      hibernate:
        ddl-auto: none
        show-sql: true
api:
  security:
    token:
      secret: my-secret-key
springdoc:
  api-docs:
    path: /docs
    pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true
    #disable-swagger-default-url: true
    path: /docs-ui